# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AllDemosInOneDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for AllDemosInOneDemo

end

flutter_application_path = '../alldemos_flutter'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)